language: ruby
rvm:
- 2.3.0
deploy:
  provider: rubygems
  api_key:
    secure: pTZrvR95IW7JyPhbOTd07RXs3umKy6rLbrLX1Ju4Deg5WDN2VjRllI6qd3FSER1geWlHh32/+FYC2zOLBf7aothlL+O/ECfUyMZ8T1fzk9RjR3/qjhP94K3/u5LfaEDFe/x3Sqmmv+bo99zaiGLu7wD3+AjJBwtr7E7s9r3TbWpRS5WIT6105QsBRYgM9Fz3hbTJW+ADHEmdqOaklERKrkVGdpacoOhC6b3OjA1fr7aHb6YplDnd5Hgb6K9ciMb3V0DFxcZMoyLsVW49CMxyeeCut6LyOZxQXwhHuBAfYvaxnWZFES0uVICGyObWm0Rc7uYTpItMVrzWfkcNjga4YXLd7ftY0jJ7K3S1loodqDYp8Fz1SkxSQ+r2Zt9S+Bj/FeQZOyqji9sezqJG3QQ43pxSsZVTlG+WQGMipsgzrXPk7LQ1oSal8q/BZhkYfPmgC62GYdTG8UjUn8Yn9NTYFnM6xKjG1TfSUyiOAXUyynGKFgUfmQi4uk5jKo6aN5jMDLLI6nE6lyoHpyAjpl9mNeSCdpeADfA0ASWO+hmuFv8riJtRzBunEA+4GvYiAPHd/aupqLzZt1f/roRSvvVlsvgUslCKk+WX+RBnEV42C8uR8zlTw6gBoH/GVxrAd3dT0HiMGAWjgqVktUe2Li8g/ywXlQV9DBlLC7+bIUcGmys=
  gem: handler_registerable
  on:
    tags: true
    repo: Sage/handler_registerable
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: bGh+Id8U+htJ540GAIXLSwW7PbCWcu5BBslFY+CBOuABgRcJSdlRuup9LAkck5GV/wYAKr5Pr2CFKh8/Euf/NEP+zpFmDJAkDx/UaR+7zyTn/PQISWpqLAX+OzUiHYCXrS8pEzPjQ8oDaAFcqDsw0EWRsq0qB/Z2ulzscw3cHNJqdVp9FNmWk77XcDrdTadOy7nVP8u95sWWAO73ChvM0Z/p/LbKRZaAu6kNtGrZQWGAFC2C22qyPVPd1qKW32s4oIjz1tbfbH+Z+rSKS4W5wL2C2AFc6A3beLnutgzriqjVvWckLUuts/CnxI9CMoFhMp4iYCjBZQnBxPYrcX7dCVFNTx+jQVCR1920hMIrpZdv4HXtyS7KNpVdwR6c9D0pX8SqdJ7WaZQxWcPjKeGVTE8iiADxcbz7mGR2LWFMdeRXPs+v+JK73ZTLqLjGLPBbc4Ti0GCReyr1YWkCMqMAvdnepMpSxderaDnN/2U5JaqKnNhf+WrbRDmrsQWQ2opgMVbzR0yLXtfhcGRdNB3qJaH7nlorxfSU/gu07KgAiBbDtTUg5oVKrF8aHpYRIvmhoPqhNNbpFDGecHKOKcEFaCpU1HLq3SJ0eGWfZmwyygxdqdnRhORzeaC2IbR3FycT/4npMKOEky1XnR6ds6T8NuJVq/WGnVB4CNHDmk/vFcE=
